[package]
name = "wasm_raylib_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raylib = { path = "raylib" }
libc = "0.2"
